# apocalypse:client_settings.toml
# This config contains various client-sided options.


# Category: difficulty_renderer
# Contains display settings for the difficulty counter shown in-game.

  # Determines the base X position on the screen where the difficulty counter should render.
  # <Enum> Valid Values: { "left", "center", "right" }, Default: "center"
  difficulty_renderer.x_anchor = "center"
  # Determines the base Y position on the screen where the difficulty counter should render.
  # <Enum> Valid Values: { "top", "center", "bottom" }, Default: "top"
  difficulty_renderer.y_anchor = "top"
  # Additional X offset for where to render the difficulty counter.
  # <Integer> Range: Any Value, Default: 0
  difficulty_renderer.x_offset = 0x000000
  # Additional Y offset for where to render the difficulty counter.
  # <Integer> Range: Any Value, Default: 2
  difficulty_renderer.y_offset = 2
  # If enabled and y_anchor is "TOP", a small Y offset is applied so we don't overlap with the boss bar when it is
  #   active.
  # <Boolean> Valid Values: { true, false }, Default: true
  difficulty_renderer.offset_boss_bar = true

  # If disabled, difficulty counter will not be displayed in creative mode.
  # <Boolean> Valid Values: { true, false }, Default: true
  difficulty_renderer.display_in_creative = true
  # If enabled, difficulty counter will only be displayed if the Apocalypse difficulty keybind is held.
  # <Boolean> Valid Values: { true, false }, Default: false
  difficulty_renderer.keybind_only = true



# Category: misc
# Some misc settings.

  # Decides the color of Apocalypse's acid rain.
  # <Integer> Range: 0x000000 ~ 0xFFFFFF, Default: 0xACFF75
  misc.acid_rain_color = 0xACFF75
  # If enabled, Apocalypse's custom weather renderer is used when it rains acid.
  # Might break if other mods are installed that changes weather rendering.
  # <Boolean> Valid Values: { true, false }, Default: true
  misc.render_acid_rain = true

