# apocalypse:events/lunar_siege.toml
# This config contains settings related to Apocalypse's Lunar Sieges / Full moon events.

  # Registry Entry List fields: General format = [ "namespace:entry_name", ... ]
  #   Registry entry lists are arrays of registry keys. Many things in the game, such as blocks or potions, are
  #     defined by their registry key within a registry. For example, all items are registered in the "minecraft:item"
  #     registry.
  #   An asterisk '*' can be used to match all registry entries/keys belonging to X namespace. For example,
  #     'minecraft:*' will match all vanilla entries.
  #   Tags can also be used here. To declare a tag, start with a '#' followed by the rest of the tag path.
  #   Tag example: '#minecraft:oak_logs'



# Category: general
# General event settings.

  # If enabled, every full moon night a 'lunar siege' will start, spawning stronger monsters and full moon monsters.
  # More settings related to this can be found further down in this config.
  # <Boolean> Valid Values: { true, false }, Default: true
  general.enable_lunar_sieges = true
  # If enabled, any mobs that are still alive that were summoned by X player's Lunar Siege event will despawn if their
  #   target player dies.
  # Can help prevent horrible spawn-camping
  # <Boolean> Valid Values: { true, false }, Default: true
  general.despawn_mobs_on_death = true



# Category: siege_mob_properties
# Various properties of full moon mobs, such as spawn amount, starting difficulty etc.

  # The amount of difficulty levels the player must pass for additional full moon mob counts to increase.
  # (This refers to the 4th value in the entries in the 'mob_spawn_settings' list below)
  # For example, a value of 30.0 means that for every time the player passes another 30.0 levels of difficulty, the
  #   amount of additional full moon mobs increases.
  # <Number> Range: 1.0 ~ 10000.0, Default: 20.0
  siege_mob_properties.difficulty_per_increase = 20.0

  # Contains various spawn settings for Full Moon siege mobs.
  # Entity types from other mods or vanilla can be added here too, if wanted.
  # This list should only contain entity type specific entries. Any tags, namespace wildcards or default values will
  #   not be used.
  # 1st value: The difficulty level required for the given mob to start spawning in sieges.
  # 2nd value: The minimum amount of the given mob type that will spawn in a full moon siege.
  # 3rd value: The maximum amount of the given mob type that can spawn in a full moon siege.
  # 4th value: Additional spawn count for the given mob type (works in conjunction with
  #   'difficulty_per_additional_increase').
  # <Registry Entry-value List> Format: [ "namespace:registry_name value1 value2 value3 value4", ... ], Default: [
  #   "apocalypse:breecher 5.0 4.0 20.0 2.0", "apocalypse:ghost 45.0 4.0 25.0 6.0", "apocalypse:grump 20.0 2.0 18.0
  #   2.5", "apocalypse:seeker 70.0 1.0 8.0 1.0", "apocalypse:destroyer 100.0 1.0 6.0 1.0" ]
  #    Target registry: ResourceKey[minecraft:root / minecraft:entity_type]
  #    Range for Values: ≥ 0.0
  siege_mob_properties.mob_spawn_settings = [
    "apocalypse:breecher 5.0 4.0 20.0 2.0",
    "apocalypse:ghost 45.0 4.0 25.0 6.0",
    "apocalypse:grump 20.0 2.0 18.0 2.5",
    "apocalypse:seeker 70.0 1.0 8.0 1.0",
    "apocalypse:destroyer 100.0 1.0 6.0 1.0"
  ]

